# Generated by Django 3.2.5 on 2021-07-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('script', models.FileField(upload_to='scripts/')),
            ],
        ),
        migrations.CreateModel(
            name='FirewallDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
