version: '3.7'

services:
  control-node-web:
    build: 
        context: ./access_server
        dockerfile: Dockerfile
    networks:
      - control-net
    command: gunicorn access_server.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/access_server_user/access_server/serve
        - media_volume:/home/access_server_user/access_server/media
    expose:
      - 8000
    env_file:
      - ./.env

  control-node-nginx:
    build: ./nginx
    networks:
      - control-net
    volumes:
        - static_volume:/home/access_server_user/access_server/serve
        - media_volume:/home/access_server_user/access_server/media
    ports:
      - 1080:80
    depends_on:
      - control-node-web

volumes:
  static_volume:
  media_volume:

networks:
  control-net:
    external: true
    name: control-net

