# Generated by Django 3.2.5 on 2021-07-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('time_to_run', models.TimeField(blank=True)),
                ('actions', models.ManyToManyField(related_name='scheduled_tasks_included_in', to='main.Action')),
                ('devices', models.ManyToManyField(related_name='scheduled_tasks_included_in', to='main.FirewallDevice')),
            ],
        ),
    ]
