---

- hosts: "{{ lookup('env', 'STATUS_HOSTNAME') }}"
  remote_user: controller
  tasks:
    - name: Ping the specified IP Ranges
      local_action: 'shell ping -a -c 1 -W 1 "{{ lookup('env', 'ADDRESS') }}"'
      register: result
      failed_when: ('100% packet loss' in result.stdout)
