---

- hosts: "{{ lookup('env', 'STATUS_HOSTNAME') }}"
  remote_user: controller
  vars:
    - address: "{{ lookup('env', 'ADDRESS') }}"
  tasks:
    - shell: "ping -a -c 1 -W 1 {{ address }}"
      register: result

    - debug: var=result.stdout_lines
